### ISSUE TITLE
Partners: Wallet Improvement Request

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/docs.skale.space#88]
Ensure wallet partners are up to date and have correct links and starting examples
```[tasklist]
### Tasks
- [ ] Add Invisible Wallet Section (Ethers, Viem, Eidolon) (remove from Custodial)
- [ ] Add Halliday (Coming Soon)
- [x] Add Dynamic.xyz -> All
- [x] Add ConnectKit -> Wallet Aggregator
- [x] Add RainbowKit -> Wallet Aggregator
- [x] Add Metakeep -> Non-custodial
- [x] Crossmint -> Custodial Wallets
```

**Comment by TheGreatAxios** [comment]
Closed as Completed
